### ISSUE TITLE
Support for new language ?

### ISSUE THREAD

**Issue by nice2meetu2** [Flo354/XposedAppLocale#10]
Could you support zn_hk (Hong Kong)? Thanks!

**Comment by Flo354** [comment]
zn_hk or zh_hk?

**Comment by nice2meetu2** [comment]
Should be zh, sorry for my typo

**Comment by Flo354** [comment]
Closed with https://github.com/Flo354/XposedAppLocale/commit/50d8fdd35a49cfc61344e75b35d47873bfd05f30

I will publish a new update in the next few days
