### ISSUE TITLE
Google assistant irregular launching behavior

### ISSUE THREAD

**Issue by HankAviator** [Flo354/XposedAppLocale#11]
1. long tap to call google assistant
2. tap back to close it
3. immediately long tap home to call it again
4. instead, google app is opened

logcat attached
[goo.txt](https://github.com/Flo354/XposedAppLocale/files/1892946/goo.txt)

**Comment by Flo354** [comment]
Does the issue occurs if the module is disabled? if XPosed is disabled?

**Comment by HankAviator** [comment]
Screenrecord attached, it doesn't behave like that when system language is set to en-US.
[ScreenRecord-2018-04-11-01-21-53.zip](https://github.com/Flo354/XposedAppLocale/files/1897221/ScreenRecord-2018-04-11-01-21-53.zip)

**Comment by Flo354** [comment]
Ok I see the problem. It seems very tricky.
Could you please attach the complete list of the app you changed language in xposedAppLocale, and the language linked to the app?

**Comment by HankAviator** [comment]
App modified | Package name | Language 
------------ | ------------- |----------
Google| com.google.android.googlequicksearchbox | en_GB
Xposed Installer | | en_US
XPrivacyLua| eu.faircode.xlua | en_GB
XPrivacyLua Pro | eu.faircode.xlua.pro | en_GB

Some other apps I think they are not involved and I'm kinda shy to post them here. I think above list is enough.

**Comment by Flo354** [comment]
There is a possible explanation. I have had weird bugs with Google assistant when I changed the language of Google App.

Try to go to device settings -> Global Management ->Lang & typing -> Vocal synthesis
Set the preferred engine to "Google", and the language to the same as Google app language. Then reboot your phone.

It may work or not work, but I don't think it's a problem with the code, more with the app itself. For instance, I use an app which get the system language from the NDK and thus, when I change the language with XPosedAppLocale, the app is in two languages (text in changed locale and voice in device locale).

**Comment by HankAviator** [comment]
Yes, I have the same feeling that Google app is very much detach inside - searching itself is applied a locale, while Google assistant doesn't comply with the locale assigned (if not system-wide).
It seems to work very well!

**Comment by HankAviator** [comment]
Well it worked well for a while... While Google app is opened, long tap home will always call Google assistant though..

**Comment by HankAviator** [comment]
Try go to Google app - hamburger menu - settings
you'll see the title, if the locale is changed via xposed module, displayed as phone i18n-ed (like on my phone, zh-CN).
Once Google assistant setting is running in background, this issue seems to be soothed.

**Comment by HankAviator** [comment]
App-related, hopefully Google gets it fixed soon.

**Comment by HankAviator** [comment]
the reason for why Google app shows instead of assistant is included in the logcat:
```
06-14 13:30:14.816 14922 14922 W AssistUtils: Now on Tap disabled because existing locale (zh_CN), is not supported (en*, es*, de*, fr*, it*, ja*, ko*, pt*, ru*)
```
`AssistUtils` method may check system locale, instead of Google app locale itself - when system language is set to English, or any supported language, this issue is gone.
A workaround on Oreo would be adding English (or any supported language) to system Language list.
@Flo354 as a reminder, it might be related with #18 - Google's apps may request system locale as well.

**Comment by Flo354** [comment]
Really good catch!

Now we know why it didn't work. So it seems that if you switch your phone locale to zh_CN, now on tap will not work eather? Am I right?

**Comment by HankAviator** [comment]
Now on tap works intermittently if:
* Google search app locale is set to a supported one

Now on tap works well if :
* Google search app locale is set to a supported one

and
* the system language is set to a supported one **only**
* the primary system language is set to an unsupported one, but a secondary language is supported (on Oreo it's possible to have more than one languages selected in system settings)
    * so I've got `zh-cn` as my primary, `en-UK` as my secondary, `ru-RU` as my tertiary.

**Comment by Flo354** [comment]
Ok I understand. But we can't do anything for that, right?

**Comment by HankAviator** [comment]
hooking `AssistUtils` will help ;)

**Comment by Flo354** [comment]
In what goal? And AssistUtils is a system class or a class within a Google app?

**Comment by HankAviator** [comment]
it's [here](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/com/android/internal/app/AssistUtils.java#L135-L157), should be a system class. This may be useful for #18

**Comment by Flo354** [comment]
Will check that when I have some free time

**Comment by HankAviator** [comment]
Unfortunately I was not entirely right, by terminating Google search app and long-tapping home key, now on tap, instead of Google search app home, is called. Seems no useful info in logcat yet.

**Comment by HankAviator** [comment]
On Oreo, system language can be more than one, the top one in the list is the primary one, selection of more languages is possible, probably as a fallback mechanism.

**Comment by Flo354** [comment]
Ok got it, thanks
